-- Run this in the Supabase SQL Editor to create the coupons table

CREATE TABLE public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('percentage', 'fixed')),
  discount_value numeric not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- Allow public read access to active coupons so they can be validated
CREATE POLICY "Allow public read access on active coupons"
ON public.coupons
FOR SELECT
USING (is_active = true);

-- Allow full access to admins only (or bypass RLS from backend service role key)
CREATE POLICY "Allow all access to authenticated admins"
ON public.coupons
FOR ALL
USING (auth.jwt() ->> 'email' = 'bizleap1@gmail.com');
